#release configuration
#Tue Jul 09 22:52:26 IST 2024
projectVersionPolicyId=default
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.org.example\:BankStatementAnalyzer.developerConnection=scm\:git\:https\://github.com/PremPrakashHessa/BankStatementAnalyzer.git
project.scm.org.example\:BankStatementAnalyzer.tag=HEAD
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
completedPhase=check-poms
scm.url=scm\:git\:https\://github.com/PremPrakashHessa/BankStatementAnalyzer.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.org.example\:BankStatementAnalyzer.connection=scm\:git\:https\://github.com/PremPrakashHessa/BankStatementAnalyzer.git
project.scm.org.example\:BankStatementAnalyzer.url=https\://github.com/PremPrakashHessa/BankStatementAnalyzer
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
